In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
calendar = "calendar.csv"
listings = "listings.csv"
reviews = "reviews.csv"

In [3]:
calendar_data = pd.read_csv(calendar)
listings_data = pd.read_csv(listings)
reviews_data = pd.read_csv(reviews)

listings_data.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,9448215,https://www.airbnb.com/rooms/9448215,2.020000e+13,1/4/2016,Capital hill,"Large room in Seattle's best neighborhood, ca...",NaN,"Large room in Seattle's best neighborhood, ca...",none,NaN,...,10.0,f,NaN,WASHINGTON,f,flexible,f,f,3,1.00
1,7204672,https://www.airbnb.com/rooms/7204672,2.020000e+13,1/4/2016,"Magnolia charm, close to downtown",Our house is just miles from the excitement of...,Our spacious home is perfect for a family or c...,Our house is just miles from the excitement of...,none,We live on a dead-end street and the house loo...,...,9.0,f,NaN,WASHINGTON,f,moderate,f,f,1,0.43
2,5579427,https://www.airbnb.com/rooms/5579427,2.020000e+13,1/4/2016,Steps from magical Discovery Park-3,A truly magnificent location in the heart of S...,WELCOME TO SEATTLE!!! I'm a professional ja...,A truly magnificent location in the heart of S...,none,"Magnolia has an ""island"" mentality and feel, t...",...,10.0,f,NaN,WASHINGTON,f,strict,f,f,4,0.74
3,6734621,https://www.airbnb.com/rooms/6734621,2.020000e+13,1/4/2016,"Super location, 3.5ba, Free Parking","This Magnolia townhouse (3 bdrm+loft, 3.5 bath...",This house was expertly picked because of loca...,"This Magnolia townhouse (3 bdrm+loft, 3.5 bath...",none,The part of Magnolia lies on the edge of Inter...,...,10.0,f,NaN,WASHINGTON,t,moderate,f,f,1,4.24
4,2263643,https://www.airbnb.com/rooms/2263643,2.020000e+13,1/4/2016,Charming English room by Park,I live near a park and also a 20 minute busrid...,"This is a large bedroom with closet, desk and ...",I live near a park and also a 20 minute busrid...,none,NaN,...,9.0,f,NaN,WASHINGTON,f,flexible,f,f,2,3.01

In [4]:
listings_df = listings_data[['id', 'neighbourhood_cleansed', 'room_type',
                            'zipcode','latitude','longitude', 'property_type', 'price','number_of_reviews',
                            'review_scores_rating', 'reviews_per_month', 'square_feet']]

listings_df.head()

,id,neighbourhood_cleansed,room_type,zipcode,latitude,longitude,property_type,price,number_of_reviews,review_scores_rating,reviews_per_month,square_feet
0,9448215,Minor,Private room,98122.0,47.611079,-122.312820,House,$67.00,1,100.0,1.00,NaN
1,7204672,Lawton Park,Entire home/apt,98199.0,47.659470,-122.401873,House,$200.00,2,90.0,0.43,NaN
2,5579427,Lawton Park,Entire home/apt,98199.0,47.654211,-122.408389,House,$229.00,4,100.0,0.74,NaN
3,6734621,Lawton Park,Entire home/apt,98199.0,47.651031,-122.385004,Townhouse,$333.00,29,94.0,4.24,NaN
4,2263643,Lawton Park,Private room,98199.0,47.659121,-122.402265,Apartment,$41.00,57,89.0,3.01,NaN

In [6]:
listings_df['price'] = pd.to_numeric(listings_df['price'].apply(lambda x:x.replace('$', '').replace(',','')))

C:\Users\brizzle\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [7]:
listings_df.head()

,id,neighbourhood_cleansed,room_type,zipcode,latitude,longitude,property_type,price,number_of_reviews,review_scores_rating,reviews_per_month,square_feet
0,9448215,Minor,Private room,98122.0,47.611079,-122.312820,House,67.0,1,100.0,1.00,NaN
1,7204672,Lawton Park,Entire home/apt,98199.0,47.659470,-122.401873,House,200.0,2,90.0,0.43,NaN
2,5579427,Lawton Park,Entire home/apt,98199.0,47.654211,-122.408389,House,229.0,4,100.0,0.74,NaN
3,6734621,Lawton Park,Entire home/apt,98199.0,47.651031,-122.385004,Townhouse,333.0,29,94.0,4.24,NaN
4,2263643,Lawton Park,Private room,98199.0,47.659121,-122.402265,Apartment,41.0,57,89.0,3.01,NaN

In [8]:
listings_df.describe()

,id,zipcode,latitude,longitude,price,number_of_reviews,review_scores_rating,reviews_per_month,square_feet
count,3.818000e+03,3811.000000,3818.000000,3818.000000,3818.000000,3818.000000,3171.000000,3191.000000,97.000000
mean,5.550111e+06,98115.696405,47.628961,-122.333103,127.976166,22.223415,94.539262,2.078919,854.618557
std,2.962660e+06,16.488203,0.043052,0.031745,90.250022,37.730892,6.606083,1.822348,671.404893
min,3.335000e+03,98101.000000,47.505088,-122.417219,20.000000,0.000000,20.000000,0.020000,0.000000
25%,3.258256e+06,98104.000000,47.609418,-122.354321,75.000000,2.000000,93.000000,0.695000,420.000000
50%,6.118244e+06,98112.000000,47.623601,-122.328874,100.000000,9.000000,96.000000,1.540000,750.000000
75%,8.035127e+06,98121.000000,47.662694,-122.310800,150.000000,26.000000,99.000000,3.000000,1200.000000
max,1.034016e+07,98199.000000,47.733358,-122.240607,1000.000000,474.000000,100.000000,12.150000,3000.000000

In [11]:
listings_df.fillna(value=0)

,id,neighbourhood_cleansed,room_type,zipcode,latitude,longitude,property_type,price,number_of_reviews,review_scores_rating,reviews_per_month,square_feet
0,9448215,Minor,Private room,98122.0,47.611079,-122.312820,House,67.0,1,100.0,1.00,0.0
1,7204672,Lawton Park,Entire home/apt,98199.0,47.659470,-122.401873,House,200.0,2,90.0,0.43,0.0
2,5579427,Lawton Park,Entire home/apt,98199.0,47.654211,-122.408389,House,229.0,4,100.0,0.74,0.0
3,6734621,Lawton Park,Entire home/apt,98199.0,47.651031,-122.385004,Townhouse,333.0,29,94.0,4.24,0.0
4,2263643,Lawton Park,Private room,98199.0,47.659121,-122.402265,Apartment,41.0,57,89.0,3.01,0.0
5,4608208,Lawton Park,Private room,98199.0,47.664035,-122.403750,House,70.0,39,98.0,3.03,0.0
6,9999955,Lawton Park,Private room,98199.0,47.651571,-122.383719,House,55.0,0,0.0,0.00,0.0
7,3528627,Lawton Park,Private room,98199.0,47.659830,-122.402738,Apartment,70.0,20,86.0,1.11,0.0
8,8048333,Lawton Park,Entire home/apt,98199.0,47.653980,-122.395548,House,97.0,0,0.0,0.00,0.0
9,8050642,Lawton Park,Entire home/apt,98199.0,47.650618,-122.403120,House,350.0,3,100.0,0.75,0.0
10,7329805,Lawton Park,Entire home/apt,98199.0,47.648992,-122.397112,House,200.0,7,94.0,1.54,0.0
11,6848455,Lawton Park,Entire home/apt,98199.0,47.649500,-122.383964,Townhouse,225.0,9,98.0,1.33,0.0
12,9695233,Lawton Park,Entire home/apt,98199.0,47.650589,-122.391016,Apartment,115.0,0,0.0,0.00,0.0
13,5164581,Lawton Park,Private room,98199.0,47.649875,-122.383561,House,40.0,58,94.0,5.26,0.0
14,2208757,Lawton Park,Entire home/apt,98199.0,47.649500,-122.382763,Townhouse,150.0,0,0.0,0.00,0.0
15,226536,Lawton Park,Private room,98199.0,47.661197,-122.401446,House,46.0,25,91.0,0.50,0.0
16,176678,Lawton Park,Private room,98199.0,47.652216,-122.385481,House,64.0,57,97.0,1.25,0.0
17,7050534,Lawton Park,Entire home/apt,98199.0,47.652438,-122.389699,Apartment,125.0,3,100.0,0.49,0.0
18,8248970,Lawton Park,Entire home/apt,98199.0,47.657950,-122.398155,House,250.0,2,100.0,0.64,0.0
19,4824699,Lawton Park,Entire home/apt,98199.0,47.654403,-122.393591,House,147.0,0,0.0,0.00,0.0
20,3876097,Lawton Park,Shared room,98199.0,47.658426,-122.402298,Bed & Breakfast,30.0,16,97.0,0.95,0.0
21,1260259,Lawton Park,Entire home/apt,98199.0,47.660564,-122.401864,House,150.0,64,100.0,2.08,0.0
22,8443952,Lawton Park,Private room,98199.0,47.649624,-122.385530,Townhouse,78.0,0,0.0,0.00,0.0
23,10068879,Lawton Park,Entire home/apt,98199.0,47.652496,-122.396354,Bed & Breakfast,120.0,0,0.0,0.00,0.0
24,8173487,Lawton Park,Entire home/apt,98199.0,47.653783,-122.388130,Condominium,280.0,2,80.0,0.50,0.0
25,685600,Lawton Park,Private room,98199.0,47.655131,-122.407818,House,75.0,8,100.0,0.47,250.0
26,8483477,Lawton Park,Entire home/apt,98199.0,47.654128,-122.389694,Apartment,178.0,1,60.0,0.30,0.0
27,10136155,Lawton Park,Entire home/apt,98199.0,47.648684,-122.383789,House,480.0,0,0.0,0.00,0.0
28,6959336,Lawton Park,Entire home/apt,98199.0,47.654382,-122.409628,House,129.0,3,73.0,0.49,0.0
29,5195064,Lawton Park,Private room,98199.0,47.650811,-122.384694,House,50.0,64,93.0,5.98,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
3788,9533648,First Hill,Entire home/apt,98101.0,47.612628,-122.324580,Apartment,103.0,7,91.0,6.00,0.0
3789,284087,First Hill,Entire home/apt,98101.0,47.611481,-122.329121,Apartment,175.0,75,94.0,1.60,0.0
3790,9097503,First Hill,Entire home/apt,98101.0,47.612479,-122.323747,Apartment,85.0,7,83.0,3.13,0.0
3791,1684236,First Hill,Entire home/apt,98101.0,47.611003,-122.328804,Apartment,100.0,49,98.0,1.82,0.0
3792,9236961,First Hill,Entire home/apt,98101.0,47.611290,-122.328943,Apartment,90.0,1,100.0,0.81,0.0
3793,8065531,First Hill,Private room,98101.0,47.611543,-122.328682,Apartment,78.0,12,97.0,2.86,0.0
3794,8342429,First Hill,Entire home/apt,98101.0,47.612279,-122.330465,Apartment,99.0,8,100.0,3.69,0.0
3795,9432322,First Hill,Entire home/apt,98101.0,47.608086,-122.327992,Apartment,72.0,0,0.0,0.00,0.0
3796,8129676,First Hill,Entire home/apt,98101.0,47.608322,-122.329996,Apartment,100.0,6,93.0,1.57,0.0
3797,4614955,First Hill,Entire home/apt,98101.0,47.612597,-122.329876,Apartment,151.0,39,93.0,3.04,0.0
3798,1043194,First Hill,Entire home/apt,98101.0,47.612885,-122.329241,Apartment,175.0,21,98.0,0.72,0.0
3799,8579782,First Hill,Entire home/apt,98101.0,47.611581,-122.329383,Condominium,140.0,3,93.0,0.99,0.0
3800,8441263,First Hill,Entire home/apt,98101.0,47.612651,-122.323922,Apartment,180.0,0,0.0,0.00,0.0
3801,3394936,First Hill,Entire home/apt,98101.0,47.611437,-122.328767,Condominium,140.0,8,98.0,0.49,0.0
3802,4752817,First Hill,Entire home/apt,98101.0,47.611683,-122.328738,Apartment,179.0,57,94.0,4.63,0.0
3803,1157083,First Hill,Entire home/apt,98101.0,47.611696,-122.329294,Apartment,245.0,18,98.0,0.58,0.0
3804,6807884,First Hill,Entire home/apt,98101.0,47.613594,-122.327840,Apartment,209.0,16,96.0,2.39,0.0
3805,1761870,First Hill,Entire home/apt,98101.0,47.612329,-122.327265,Apartment,125.0,0,0.0,0.00,0.0
3806,4250639,Broadway,Entire home/apt,98101.0,47.613876,-122.329277,Apartment,139.0,4,95.0,0.34,0.0
3807,9509279,Broadway,Entire home/apt,98101.0,47.615062,-122.322740,Apartment,100.0,4,80.0,2.93,0.0
3808,8050232,Broadway,Entire home/apt,98101.0,47.613909,-122.329030,Apartment,90.0,10,74.0,2.48,0.0
3809,3394837,Broadway,Entire home/apt,98101.0,47.613270,-122.329470,Apartment,140.0,7,97.0,0.90,0.0
3810,1198884,Broadway,Entire home/apt,98101.0,47.613301,-122.329932,Apartment,150.0,63,93.0,2.00,0.0
3811,2039149,West Woodland,Entire home/apt,0.0,47.666868,-122.364031,House,225.0,121,91.0,5.15,0.0
3812,610989,North Queen Anne,Private room,0.0,47.649393,-122.375583,Bed & Breakfast,209.0,1,100.0,0.04,0.0
3813,4172364,Leschi,Private room,0.0,47.604754,-122.294383,House,55.0,33,97.0,3.46,0.0
3814,8355276,Yesler Terrace,Entire home/apt,0.0,47.604879,-122.322308,Apartment,65.0,14,87.0,4.62,0.0
3815,2134911,Interbay,Private room,0.0,47.661186,-122.385344,Boat,95.0,5,92.0,0.27,300.0
3816,2332949,Portage Bay,Entire home/apt,0.0,47.645867,-122.321416,House,380.0,38,95.0,1.91,0.0
3817,9774404,Broadway,Entire home/apt,0.0,47.617062,-122.325872,Apartment,100.0,0,0.0,0.00,0.0

In [12]:
listings_df['square_feet'].isnull().sum()

3721

In [ ]:
# listings_df['zipcode'].isnull().sum()

In [ ]:
# listings_df = listings_df.dropna(axis=0)

In [ ]:
listings_df['property_type'].value_counts()

In [ ]:
listings_df['potential_annual_revenue']= listings_df['price']*365*.33

In [ ]:
zipcode_values = pd.read_csv('HV_zipcode.csv', encoding='latin1')

values = zipcode_values[['RegionName', 'Zhvi']]
values = values.rename(columns={'RegionName':'zipcode', 'Zhvi': 'Zillow_Avg_Value'})
values

In [ ]:
merged_df = pd.merge(listings_df, values, how='left', on=['zipcode', 'zipcode'])

In [ ]:
merged_df.head()

In [ ]:
merged_df['yield']= merged_df['potential_annual_revenue'] / merged_df['Zillow_Avg_Value'] *100
merged_df['rent_squre_foot']= merged_df['potential_annual_revenue'] / merged_df['square_feet']
merged_df['rent_squre_foot'] = merged_df['rent_squre_foot'].apply(lambda x: round(x,2))



merged_df.head()

In [ ]:
merged_df.to_csv('cleaned_data.csv')